version: 0.1.{build}
image: Visual Studio 2022
environment:
  main_project: oscript-component
before_build:
- ps: nuget restore
init:
- REG ADD "HKLM\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 65001>nul" /f
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- cmd: >-
    mkdir engine

    cd engine

    appveyor DownloadFile https://oscript.io/downloads/preview/OneScript-2.0.0-rc4-fdd-x64.zip -FileName fdd.zip

    7z x fdd.zip > NUL

    set PATH=%cd%\bin;%PATH%

    cd ..

    appveyor DownloadFile https://github.com/dmpas/OneScriptDocumenter/releases/download/1.0.13/documenter.zip -FileName OneScriptDocumenter.zip

    7z x OneScriptDocumenter.zip > NUL

    oscript -version

    opm install opm

build:
  verbosity: minimal
configuration: Release

after_build:
- cmd: >-

    del %main_project%\bin\%CONFIGURATION%\netstandart2.1\*.pdb

    mkdir bin

    OneScriptDocumenter.exe json bin\syntaxHelp.json %main_project%\bin\%CONFIGURATION%\netstandart2.1\%main_project%.dll
    
    del %main_project%\bin\%CONFIGURATION%\ScriptEngine*.* %main_project%\bin\%CONFIGURATION%\netstandart2.1\NewtonSoft*.* %main_project%\bin\%CONFIGURATION%\netstandart2.1\DotNetZip*.*
    
    xcopy %main_project%\bin\%CONFIGURATION%\* bin\
    
    opm build .
    
    for %%X in (*.ospx) do (opm install -f %%X )
    
    cd ..

artifacts:
- path: .\*.ospx
  name: component